/**
 * List of excluded restaurant chains
 * These chains will be filtered out from job listings
 */

const EXCLUDED_RESTAURANT_CHAINS = [
    // Fast food chains
    "McDonald's",
    "Burger King",
    "Wendy's",
    "KFC",
    "Taco Bell",
    "Subway",
    "Domino's",
    "Pizza Hut",
    "Dunkin' Donuts",
    "Starbucks",
    "Chipotle",
    "Chick-fil-A",
    "Popeyes",
    "Arby's",
    "Dairy Queen",
    "Jack in the Box",
    "Hardee's",
    "Carl's Jr.",
    "Sonic Drive-In",
    "Whataburger",
    "Five Guys",
    "In-N-Out Burger",
    "White Castle",
    "Shake Shack",
    "Zaxby's",
    "Raising Cane's",
    "Culver's",
    "Bojangles",
    "Church's Chicken",
    "Little Caesars",
    "Papa John's",
    "Jimmy John's",
    "Jersey Mike's",
    "Firehouse Subs",
    "Panera Bread",
    "Panda Express",
    "Qdoba",
    "Moe's Southwest Grill",
    "Wingstop",
    "Buffalo Wild Wings",
    "Applebee's",
    "Chili's",
    "TGI Fridays",
    "Olive Garden",
    "Red Lobster",
    "Outback Steakhouse",
    "Texas Roadhouse",
    "Cracker Barrel",
    "IHOP",
    "Denny's",
    "Waffle House",
    "Bob Evans",
    "Ruby Tuesday",
    "Red Robin",
    "Cheesecake Factory",
    "P.F. Chang's",
    "Baskin-Robbins",
    "Cold Stone Creamery",
    "Krispy Kreme",
    "Cinnabon",
    "Auntie Anne's",
    "Jamba Juice",
    "Smoothie King",
    
    // Additional chains from the provided list
    "Zaxby's",
    "Wow Bao",
    "WingStreet",
    "Wimpy",
    "Whataburger",
    "Wetherspoons",
    "Wendy's",
    "Wallace",
    "Waffle House",
    "Vkusno i Tochka",
    "Ting Hsin International Group",
    "Tim Hortons",
    "Texas Roadhouse",
    "Telepizza",
    "Tastien",
    "Taco Bell",
    "Sukiya",
    "Subway",
    "Steers",
    "Steak 'n Shake",
    "Starbucks",
    "Sonic Drive-In",
    "Smoothie King",
    "Shakey's Pizza",
    "Shake Shack",
    "SFC Plus",
    "Sbarro",
    "Round Table Pizza",
    "Rita's Italian Ice",
    "Raising Cane's Chicken Fingers",
    "Quiznos",
    "Qdoba",
    "Popeyes",
    "Pizza Pizza",
    "Pizza Hut",
    "Pita Pit",
    "Pelicana Chicken",
    "Papa Murphy's",
    "Papa John's",
    "Panera Bread",
    "Panda Express",
    "Pala Hamburger",
    "Orange Julius",
    "Olive Garden",
    "Nando's",
    "MrBeast Burger",
    "MOS Burger",
    "Moe's Southwest Grill",
    "Mixue Ice Cream & Tea",
    "Mi Bibimbap",
    "McDonald's",
    "Mang Inasal",
    "Luckin Coffee",
    "Long John Silver's",
    "Little Caesars",
    "Kwafood",
    "Kungfu",
    "Krispy Kreme",
    "KFC",
    "Kebab Turki Baba Rafi",
    "Jollibee",
    "Jimmy John's",
    "Jersey Mike's Subs",
    "Jack in the Box",
    "IHOP",
    "Ichibanya",
    "Hunt Brothers Pizza",
    "Hungry Howie's",
    "Home Original Chicken",
    "Hey Tea",
    "Hesburger",
    "Hardee's",
    "Häagen-Dazs",
    "Greggs",
    "Good me",
    "Gloria Jean's Coffees",
    "Freddy's Frozen Custard & Steakburgers",
    "Five Guys",
    "Firehouse Subs",
    "Einstein Bros. Bagels",
    "Dunkin' Donuts",
    "Domino's",
    "Dodo Pizza",
    "Dicos",
    "Denny's",
    "Del Taco",
    "Dairy Queen",
    "Da Niang Dumpling",
    "Culver's",
    "Cotti Coffee",
    "Costa Coffee",
    "Cold Stone Creamery",
    "Cinnabon",
    "Church's Texas Chicken",
    "Chuck E. Cheese",
    "Chooks-to-Go",
    "Chipotle Mexican Grill",
    "Chili's",
    "Chick-fil-A",
    "Chester's",
    "Checkers and Rally's",
    "Charleys Philly Steaks",
    "ChaPanda",
    "Chagee",
    "Carl's Jr.",
    "Captain D's",
    "Café Coffee Day",
    "Burger King",
    "Buffalo Wild Wings",
    "Brioche Dorée",
    "BreadTalk",
    "Boost Juice",
    "Bojangles' Famous Chicken 'n Biscuits",
    "Bob's",
    "Blimpie",
    "Baskin-Robbins",
    "Auntie Anne's",
    "Auntea Jenny",
    "Arby's",
    "Applebee's",
    "A&W Restaurants",
    "A&W (Canada)",
    "85°C Bakery Cafe"
];

export { EXCLUDED_RESTAURANT_CHAINS };
